# Week 2 — SQL for Data Science
##  Objectives
The object of week 2 is to understand relational databases,learn how to retrive data using SQL, practice SELECT, WHERE and basic filtering, ORDER BY, GROUP BY, INNER JOIN, LEFT JOIN, RIGHT JOIN and also practice aggregate functions like COUNT(),
SUM(), AVG(), MIN(), MAX() and also to solve the 15-20 SQL practice  problems

In [3]:
import sqlite3
import pandas as pd

print("Libraries imported successfully!")
print("Pandas version:", pd.__version__)

Libraries imported successfully!
Pandas version: 3.0.6

## 1. Create SQLite Database

SQLite is used to store and query our sample sales data.

In [4]:
conn = sqlite3.connect("sales_database.db")

print("Database connected successfully!")

Database connected successfully!

## 2. Create Tables
here to create the table i will use four tables customers, products, orders, order_items

In [5]:
conn.executescript("""
CREATE TABLE IF NOT EXISTS customers (
    customer_id INTEGER PRIMARY KEY,
    customer_name TEXT,
    city TEXT,
    age INTEGER
);

CREATE TABLE IF NOT EXISTS products (
    product_id INTEGER PRIMARY KEY,
    product_name TEXT,
    category TEXT,
    price REAL
);

CREATE TABLE IF NOT EXISTS orders (
    order_id INTEGER PRIMARY KEY,
    customer_id INTEGER,
    order_date TEXT
);

CREATE TABLE IF NOT EXISTS order_items (
    order_item_id INTEGER PRIMARY KEY,
    order_id INTEGER,
    product_id INTEGER,
    quantity INTEGER
);
""")

print("Tables created successfully!")

Tables created successfully!

## 3. Insert Sample Data

In [7]:
customers = [
    (1, "Ram", "Kathmandu", 22),
    (2, "Sita", "Pokhara", 25),
    (3, "Hari", "Janakpur", 21),
    (4, "Anita", "Kathmandu", 28),
    (5, "Bikash", "Biratnagar", 30)
]

products = [
    (1, "Laptop", "Electronics", 80000),
    (2, "Mouse", "Electronics", 1500),
    (3, "Keyboard", "Electronics", 3000),
    (4, "Chair", "Furniture", 15000),
    (5, "Notebook", "Stationery", 200)
]

orders = [
    (101, 1, "2026-09-01"),
    (102, 2, "2026-09-02"),
    (103, 3, "2026-09-03"),
    (104, 1, "2026-09-04"),
    (105, 4, "2026-09-05")
]

order_items = [
    (1, 101, 1, 1),
    (2, 101, 2, 2),
    (3, 102, 4, 1),
    (4, 103, 5, 5),
    (5, 104, 3, 1),
    (6, 105, 4, 2)
]

conn.executemany("INSERT OR IGNORE INTO customers VALUES (?, ?, ?, ?)", customers)
conn.executemany("INSERT OR IGNORE INTO products VALUES (?, ?, ?, ?)", products)
conn.executemany("INSERT OR IGNORE INTO orders VALUES (?, ?, ?)", orders)
conn.executemany("INSERT OR IGNORE INTO order_items VALUES (?, ?, ?, ?)", order_items)

conn.commit()

print("Sample data inserted successfully!")

Sample data inserted successfully!

## 4. View the Tables
### Customer

In [8]:
pd.read_sql("SELECT * FROM customers", conn)

   customer_id customer_name        city  age
0            1           Ram   Kathmandu   22
1            2          Sita     Pokhara   25
2            3          Hari    Janakpur   21
3            4         Anita   Kathmandu   28
4            5        Bikash  Biratnagar   30

### product

In [10]:
pd.read_sql("SELECT * FROM products;", conn)

   product_id product_name     category    price
0           1       Laptop  Electronics  80000.0
1           2        Mouse  Electronics   1500.0
2           3     Keyboard  Electronics   3000.0
3           4        Chair    Furniture  15000.0
4           5     Notebook   Stationery    200.0

### orders

In [11]:
pd.read_sql("SELECT * FROM orders;", conn)

   order_id  customer_id  order_date
0       101            1  2026-09-01
1       102            2  2026-09-02
2       103            3  2026-09-03
3       104            1  2026-09-04
4       105            4  2026-09-05

### Order_items

In [12]:
pd.read_sql("SELECT * FROM order_items;", conn)

   order_item_id  order_id  product_id  quantity
0              1       101           1         1
1              2       101           2         2
2              3       102           4         1
3              4       103           5         5
4              5       104           3         1
5              6       105           4         2

## 5. SQL Practice Problems
Here area the queries of practicing SELECT, WHERE, ORDER BY, GROUP BY,
aggregate functions and JOINs.

### SELECT

In [15]:
pd.read_sql("SELECT * FROM customers;", conn)

   customer_id customer_name        city  age
0            1           Ram   Kathmandu   22
1            2          Sita     Pokhara   25
2            3          Hari    Janakpur   21
3            4         Anita   Kathmandu   28
4            5        Bikash  Biratnagar   30

### Selecting  specific colum from Customer

In [16]:
pd.read_sql("""
SELECT customer_name, city
FROM customers;
""", conn)

  customer_name        city
0           Ram   Kathmandu
1          Sita     Pokhara
2          Hari    Janakpur
3         Anita   Kathmandu
4        Bikash  Biratnagar

### WHERE

In [17]:
pd.read_sql("""
SELECT *
FROM customers
WHERE age > 25;
""", conn)

   customer_id customer_name        city  age
0            4         Anita   Kathmandu   28
1            5        Bikash  Biratnagar   30

### Filtering

In [18]:
pd.read_sql("""
SELECT *
FROM customers
WHERE city = 'Kathmandu';
""", conn)

   customer_id customer_name       city  age
0            1           Ram  Kathmandu   22
1            4         Anita  Kathmandu   28

### AND

In [19]:
pd.read_sql("""
SELECT *
FROM customers
WHERE city = 'Kathmandu' AND age > 25;
""", conn)

   customer_id customer_name       city  age
0            4         Anita  Kathmandu   28

### ORDER BY

In [20]:
pd.read_sql("""
SELECT product_name, price
FROM products
ORDER BY price ASC;
""", conn)

  product_name    price
0     Notebook    200.0
1        Mouse   1500.0
2     Keyboard   3000.0
3        Chair  15000.0
4       Laptop  80000.0

### DESC

In [21]:
pd.read_sql("""
SELECT product_name, price
FROM products
ORDER BY price DESC;
""", conn)

  product_name    price
0       Laptop  80000.0
1        Chair  15000.0
2     Keyboard   3000.0
3        Mouse   1500.0
4     Notebook    200.0

### Count

In [22]:
pd.read_sql("""
SELECT COUNT(*) AS total_customers
FROM customers;
""", conn)

   total_customers
0                5

### SUM

In [23]:
pd.read_sql("""
SELECT SUM(quantity) AS total_quantity
FROM order_items;
""", conn)

   total_quantity
0              12

### AVG

In [24]:
pd.read_sql("""
SELECT AVG(age) AS average_age
FROM customers;
""", conn)

   average_age
0         25.2

### MIN

In [25]:
pd.read_sql("""
SELECT MIN(price) AS minimum_price
FROM products;
""", conn)

   minimum_price
0          200.0

### MAX

In [26]:
pd.read_sql("""
SELECT MAX(price) AS maximum_price
FROM products;
""", conn)

   maximum_price
0        80000.0

### GROUP BY

In [27]:
pd.read_sql("""
SELECT city, COUNT(*) AS customer_count
FROM customers
GROUP BY city;
""", conn)

         city  customer_count
0  Biratnagar               1
1    Janakpur               1
2   Kathmandu               2
3     Pokhara               1

### INNER JOIN

In [28]:
pd.read_sql("""
SELECT
    customers.customer_name,
    orders.order_id,
    orders.order_date
FROM customers
INNER JOIN orders
ON customers.customer_id = orders.customer_id;
""", conn)

  customer_name  order_id  order_date
0           Ram       101  2026-09-01
1          Sita       102  2026-09-02
2          Hari       103  2026-09-03
3           Ram       104  2026-09-04
4         Anita       105  2026-09-05

### LEFT JOIN

In [29]:
pd.read_sql("""
SELECT
    customers.customer_name,
    orders.order_id
FROM customers
LEFT JOIN orders
ON customers.customer_id = orders.customer_id;
""", conn)

  customer_name  order_id
0           Ram     101.0
1           Ram     104.0
2          Sita     102.0
3          Hari     103.0
4         Anita     105.0
5        Bikash       NaN

### RIGHT JOIN

In [30]:
pd.read_sql("""
SELECT
    customers.customer_name,
    orders.order_id
FROM customers
RIGHT JOIN orders
ON customers.customer_id = orders.customer_id;
""", conn)

  customer_name  order_id
0           Ram       101
1           Ram       104
2          Sita       102
3          Hari       103
4         Anita       105

## Business Questions
Here are the 10 business question with SQL queries answer about the customers, products, orders and the sales

## 1. How many Customers arre there?

In [31]:
pd.read_sql("""
SELECT COUNT(*) AS total_customers
FROM customers;
""", conn)

   total_customers
0                5

## 2. How many customers are in each city?

In [32]:
pd.read_sql("""
SELECT city, COUNT(*) AS customers
FROM customers
GROUP BY city;
""", conn)

         city  customers
0  Biratnagar          1
1    Janakpur          1
2   Kathmandu          2
3     Pokhara          1

## 3. What is the average customer age?

In [33]:
pd.read_sql("""
SELECT AVG(age) AS average_age
FROM customers;
""", conn)

   average_age
0         25.2

## 4. What is the most expensive product?

In [34]:
pd.read_sql("""
SELECT product_name, price
FROM products
ORDER BY price DESC
LIMIT 1;
""", conn)

  product_name    price
0       Laptop  80000.0

## 5. What is the cheapest product?

In [35]:
pd.read_sql("""
SELECT product_name, price
FROM products
ORDER BY price ASC
LIMIT 1;
""", conn)

  product_name  price
0     Notebook  200.0

## 6. How many products are in each category?

In [36]:
pd.read_sql("""
SELECT category, COUNT(*) AS product_count
FROM products
GROUP BY category;
""", conn)

      category  product_count
0  Electronics              3
1    Furniture              1
2   Stationery              1

## 7. How many orders has each customer placed?

In [37]:
pd.read_sql("""
SELECT
    customers.customer_name,
    COUNT(orders.order_id) AS total_orders
FROM customers
LEFT JOIN orders
ON customers.customer_id = orders.customer_id
GROUP BY customers.customer_name;
""", conn)

  customer_name  total_orders
0         Anita             1
1        Bikash             0
2          Hari             1
3           Ram             2
4          Sita             1

## 8. Which products were ordered?

In [38]:
pd.read_sql("""
SELECT
    products.product_name,
    SUM(order_items.quantity) AS quantity_sold
FROM products
INNER JOIN order_items
ON products.product_id = order_items.product_id
GROUP BY products.product_name;
""", conn)

  product_name  quantity_sold
0        Chair              3
1     Keyboard              1
2       Laptop              1
3        Mouse              2
4     Notebook              5

## 9. Which customer bought which product?

In [39]:
pd.read_sql("""
SELECT
    customers.customer_name,
    products.product_name,
    order_items.quantity
FROM customers
JOIN orders
ON customers.customer_id = orders.customer_id
JOIN order_items
ON orders.order_id = order_items.order_id
JOIN products
ON order_items.product_id = products.product_id;
""", conn)

  customer_name product_name  quantity
0           Ram       Laptop         1
1           Ram        Mouse         2
2          Sita        Chair         1
3          Hari     Notebook         5
4           Ram     Keyboard         1
5         Anita        Chair         2

## 10. What is the total sales value for each product?

In [40]:
pd.read_sql("""
SELECT
    products.product_name,
    SUM(products.price * order_items.quantity) AS total_sales
FROM products
JOIN order_items
ON products.product_id = order_items.product_id
GROUP BY products.product_name
ORDER BY total_sales DESC;
""", conn)

  product_name  total_sales
0       Laptop      80000.0
1        Chair      45000.0
2        Mouse       3000.0
3     Keyboard       3000.0
4     Notebook       1000.0

## Close Database

In [41]:
conn.close()

print("Database connection closed.")

Database connection closed.